theme: jekyll-theme-minimal
title: Welcome!
description: Amir Arslan Haghrah | امیر ارسلان حق ره
logo: /assets/avatar.jpg
fontname: amiri
fontsize: 18
fontttf: /assets/amiri.ttf
fontwoff: /assets/amiri.woff
fontwoff2: /assets/amiri.woff2
author: Arslan
permalink: /blog/:year/:month/:day/:title
markdown: kramdown
