theme: jekyll-theme-minimal
title: Welcome to my page!
description: Some general information about myself!
logo: [https://avatars3.githubusercontent.com/u/7789561?s=460&u=fdbc8bd1a74759bc250cf25519f31241d4d9b2f0&v=4]
